### PR TITLE
Add support for haplotag reads

### PR DESCRIPTION
**Pull request by EdHarry**
- init
- haplotag support
- haplotag support

Adds support for haplotag barcodes (https://www.biorxiv.org/content/10.1101/2020.05.25.113688v2 https://github.com/evolgenomics/haplotagging)
Haplotag barcodes take the form 'AxxCxxBxxDxx' where 'xx' are numbers in the range [01 - 96], and are placed in BX tags

The barcodes are encoded into uint32_t by 'AaaCccBbbDdd' -> (aa << 24) | (cc << 16) | (bb << 8) | (dd)

Adds:
-p option to ema count for haplotag mode, only outputs *.ema-ncnt in this mode

-p option to ema preproc for haplotag mode, no error correction is performed in this mode (haplotag barcodes are pre-corrected)
	can output in BX format or ema fastq format

"haptag" option for platform (-p) to ema align, can process standard fastq format with BX tags or ema fastq format

### CODE REVIEW

**Comment by pdimens** [comment]
Will this PR see any integration into EMA? It has tremendous value in increasing the adoption of Haplotagging

**Comment by pdimens** [comment]
@EdHarry how does this modification handle missing barcodes `00`, such as `A00B12C33D14`?

**Comment by pdimens** [comment]
@arshajii I compiled the latest version and a few things pop up immediately:
1. ema count does not recognize the `-p` flag
```
$ ./interleave.sh file1.R1.fq.gz file2.R2.fq.gz  | ../ema/ema count -p -w whitelist.txt  -o ematest

count: invalid option -- 'p'
usage: ../ema/ema <count|preproc|align|help> [options]
```
2. Docstrings from `--help` dont list -p as an option for `count` or `preproc`
3. Docstring from `--help` for `align` does not list `haplotag` as an option

**Comment by pdimens** [comment]
Another small note, sort of unrelated, is that the docstring for `align` is missing a newline character before `-t threads`

**Comment by pdimens** [comment]
@EdHarry What do the `GenerateAllHaplotagBC` and `GenerateAllHaplotagBC_Field` functions do? I'm trying to understand the logic, but lack C++ literacy. My hope is to make the parsing sections you wrote generalizable for the different emerging haplotagging barcoding protocols.

**Comment by arshajii** [comment]
Hi @pdimens, I haven't had too much time to look into this the past few days, but based on some of your messages here are a couple observations/clarifications:

- Again I'm not too familiar with haplotag barcodes and all the datatypes involved, but it appears that `GenerateAllHaplotagBC[_field]` is just zeroing out all possible haplotag encodings in the `counts` map. The 4 `for`-loops iterate over `{1, 2, ..., 96} ^ 4`, encode the corresponding haplotag with `PackHaplotag`, and then set its entry in the map to zero.
- For the segfault: In the changed code, that function is only being called if `is_haplotag` is false (i.e. see `encode_bc`). I would assume this flag is not being set when mapping when it should be.

**Comment by pdimens** [comment]
Thanks! My understanding is that GenerateAll circumvents including a whitelist, which isn't really necessary. Would you know where to make the change to prevent the segfault ?

**Comment by prmunn** [comment]
Hi @EdHarry and @arshajii  - I'm getting the same "ema: src/util.c:54: encode_bc_default: Assertion `0' failed" error when running the EdHarry:haplotag branch of the code. Any thoughts on how to fix this?

**Comment by prmunn** [comment]
Hi @EdHarry and @arshajii - it turns out I was running the code from @EdHarry s master branch instead of the more recent code in the haplotag branch. When I used the more recent code it worked without crashing. Would it be possible to merge the haplotag branch, since I know of at least one other person that cloned from the master branch by mistake.

**Comment by pdimens** [comment]
@arshajii I have been using the this fork (`haplotag` branch) for months now without issue. May this be merged into EMA?

**Comment by pdimens** [comment]
@arshajii I would like to host [harpy](https://github.com/pdimens/harpy) on bioconda, however I cannot do so without these haplotag changes being incorporated into a new release of `ema` and the package recipe being updated on bioconda. I understand your bandwidth is limited and can take on this effort if given collaborator permissions on this repository.

**Comment by arshajii** [comment]
Hi @pdimens -- apologies for the delays. Happy to make you a collaborator; I'll do it now. Please feel free to merge this and/or make other additions as you see fit.

**Comment by pdimens** [comment]
Thank you @arshajii . Are you comfortable with me also updating the conda release after?

**Comment by arshajii** [comment]
Absolutely. Appreciate your effort :) Sorry again for the slowness on my side; things have been very busy for me lately.

**Pull request merged**
